### ISSUE TITLE
TR Entry point for Cosmos input files crashes with multiple inputs

### ISSUE THREAD

**Issue by enoriega** [ml4ai/skema#101]
Whenever the TR pipeline using the `AnnotateCosmosJsonFiles` with several inputs the underlying odin engine crashes. Running one process per input file doesn't fail, but is extremely time consuming.

**Comment by kwalcock** [comment]
With multiple files being processed in parallel plus a lazy val for the pipeline, there's a chance that some parts of the pipeline will get used before they are completely ready.  If it's difficult to track down the real problem, you might skip the lazy and possibly run one tiny text through the pipeline first to ensure that everything is properly initialized before flooding it with parallel requests.

**Comment by enoriega** [comment]
Good catch! Thanks @kwalcock
