### ISSUE TITLE
De-duplicate Json Serialization

### ISSUE THREAD

**Issue by enoriega** [ml4ai/skema#120]
The class `AutomatesAttachment` has two redundant json serialization abstract methods.

It looks like only one of them  is used: `toUJson`. The other one, which uses Play!'s json api may be vestigial, but it is unclear.

Unless there is a good reason to support to parallel implementations of json serialization, we should stick to the uJson and remove the other one.

**Comment by kwalcock** [comment]
A typical reason for this is the need to serialize in a webapp.  There the output is expected to be a Play json object and if someone has previously used ujson, this leads to either adding the additional code or taking the ujson, converting to a string, and then parsing for Play, which is inefficient.  I don't know the circumstances here or the future.  I'd probably be conservative and just comment out the code in case it needs to be used after all.  It's unlikely that people will know to go back through the git history to recover the old version if the need arises.

**Comment by enoriega** [comment]
Fair enough. Let's do this instead of removing PlayJson from the dependencies
