### ISSUE TITLE
Create an pure text TR Pipeline

### ISSUE THREAD

**Issue by enoriega** [ml4ai/skema#153]
Add an additional pipeline that takes as input a pure text file. Currently we expect COSMOS' join format, but we should be able to do process plain text files as well

**Comment by kwalcock** [comment]
I was still wondering about OpenAPI documentation for the output.  It's a very large and complex data structure.

**Comment by enoriega** [comment]
What is the most efficient way to give you the documentation to most of the fields?
I am thinking about a json file with the same structure but that has variable descriptions instead of real values

**Comment by kwalcock** [comment]
That would be great!  On the first pass I was just going to call the API and document the result as far as names, types, and structure, but the description would be hard for me to generate.  Then I would need to go through the code and clean up anything that doesn't happen to appear in the output.  I actually just found an existing spec for processor output (document, sentences, edges, etc.) that I can copy.  So, it's only the things specific to skema that need to be filled in.

**Comment by enoriega** [comment]
That sounds good.

**Comment by kwalcock** [comment]
I'll add documentation in a separate PR.

**Comment by kwalcock** [comment]
It's in #182.
