### ISSUE TITLE
Add free text grounding endpoint to the TR Web API

### ISSUE THREAD

**Issue by enoriega** [ml4ai/skema#154]
We should have an endpoint on the API that allows to annotate arbitrary strings with the TR pipeline. The endpoint should support multiple inputs, probably as a json array in the payload of the request, in order to support batch annotations.
Finally, there should be documentation for this endpoint in the Yaml file to test it.

Example:

Use a `POST` request to send the phrase `the initial rate of infection is of 5` to the API, and return the json output with a mention extracted by it.

**Comment by kwalcock** [comment]
That seems like something good for me, and questions will probably follow.  I'm blissfully unaware of scheduling, though, so could you add a hint regarding due date just in case it is an issue?

**Comment by enoriega** [comment]
This is a soft deadline: if it can be ready before next Wednesday we can report it on the next TA1 meeting. If it takes more time, there's no problem.

**Comment by kwalcock** [comment]
@enoriega, the description is sounding a lot like what the webapp does, although it doesn't look like the webapp does the grounding that is in the issue title.  Do you just need the webapp's /parseSentence to be documented and callable from the swagger interface?  There is also a json_doc_to_mentions that would probably just need something small to make it text_doc_to_mentions.  Is each string/sentence supposed to be a separate document?  Are multiple strings/sentences supposed to be combined into a single document and then does there need to be multiple of these multiple-sentence documents processed in a single API call?  json_doc_to_mentions doesn't ground, either.  There are lots of grounding endpoints and some work on Mentions,  How should mentions be grounded, if at all?

**Comment by enoriega** [comment]
Good points. In PR #157 I introduced `TextReadingPipelineWithContext`. This end point should look `/parseSentence`, but using this new pipeline more or less like this:

```scala
val pipeline = new TextReadingPipelineWithContext(contextWindowSize = 3)

val annotations = 
  for(inputText <- request.body.fromJson.inputTexts) yield {
    pipeline.extractMentionsWithContextAndSerialize(inputText)
  }

annotations.toJson
```

We are deprecating (and soon deleting) `/parseSentence`, `/json_doc_to_mentions` and all those grounding endpoints. They're inherited from automates, but the goal is to eventually move all the business logic into those pipeline instances, and remove it from the web controller.
