### ISSUE TITLE
Rename dependency to accurately describe the domain

### ISSUE THREAD

**Issue by enoriega** [ml4ai/skema#159]
The word embeddings model for the epidemiology domain is contained in a resource named `model_streamed_trigram.data`.
Since we are adding support for the space weather domain for grounding, we need unambiguous names.

Can we rename it to `epidemiology_embeddings_model.data` or something similar? This will require to update `application.conf`, `build.sbt` and artifactory with the correct file names.

**Comment by kwalcock** [comment]
I did see this and will get to it soon(ish).

**Comment by kwalcock** [comment]
Please see #162.  I wasn't sure what to change in `appication.conf`, but the resources was named in `MiraEmbeddingsGrounder.scala` where I changed it.

**Comment by enoriega** [comment]
Thanks @kwalcock ! I will double check application.conf and the grounder to make sure it is not hard coded
