### ISSUE TITLE
Jar the SW embedding models for our usage

### ISSUE THREAD

**Issue by enoriega** [ml4ai/skema#163]
Our colleagues from UWisc have trained a few word embedding models based on a _Space Weather_ corpus.
They're available for download from [here](https://xdd.wisc.edu/app_output/spaceweather_word2vec.zip).

Can you please jar them and post them to our artifactory for import through sbt? I think we should have a jar for each model (`{uni,bi,tri}gram`) and we can choose which to load through the dependencies.

**Comment by enoriega** [comment]
@kwalcock just checking if you had a chance to look at this. Would it be possible for at least one of the models to be online by Apr 18th?

**Comment by kwalcock** [comment]
It's on the calendar for tomorrow.

**Comment by enoriega** [comment]
thanks!

**Comment by kwalcock** [comment]
@enoriega,

These pictured are the files, but they aren't normal glove files.  Do they need to be read in with gensim and converted to the right format?  Otherwise I don't understand what I'm seeing.

```
kwa@KWA-Aorus-Ubuntu:~/share$ head -3 model_default_streamed_bigram 
�cgensim.models.word2vec
Word2Vec
q)�q}q(Xmax_final_vocabqNX	callbacksq)Xloadqcgensim.utils
```


![image](https://user-images.githubusercontent.com/8679738/232196250-7db49cc6-d94f-443d-80cf-f16dcf22dd40.png)

**Comment by enoriega** [comment]
Yes, they're keyed vectors that hace to be read with gensim. I think they can be saved as a text file after loading

**Comment by kwalcock** [comment]
@enoriega, this seems to be working.  To `build.sbt` one needs to add a line with either unigram, bigram, or trigram like
```scala
    "org.clulab"                  % "spaceweather-model-unigram-ser"      % "1.0.0",
```
and then in some file that needs the resource something like
```scala
      case None => loadWordEmbeddingsFromResource("/org/clulab/spaceweather/spaceweather_model_unigram.ser")
```
I believe that these files are located on Kate, which is having problems.  They downloaded without error for me, but I think there were a few internal retries.  A few more tries and it would have errored out.

**Comment by enoriega** [comment]
Thanks! This should be good. I hope we find a solution for Kate soon.
