### ISSUE TITLE
Automatically build TR Docker Image upon merge

### ISSUE THREAD

**Issue by enoriega** [ml4ai/skema#164]
Is it possible to automatically build a new docker image and post it on docker hub, with an automatic minor version bump each time a PR related to text reading is merged?

We still don't have a defined docker hub account for this project but can use mine while we get the official one.

**Comment by myedibleenso** [comment]
We could publish images under the `lumai` namespace fairly easily.  Is that acceptable?  

@enoriega , can you flesh out which images need to be published with each merge? Please include the build instructions for each image you need.

**Comment by enoriega** [comment]
Using Lum's account is fine for me.
The only image I refer to is describe on this [docker file](https://github.com/ml4ai/skema/blob/main/skema/text_reading/text_reading/Dockerfile). However, there are a few others in the project that we might want to do this for too (cc. @adarshp)
One minor caveat is that the aforementioned docker file builds an `x86_64` image and not an `ARM64` one. Is this something that can be easily customized in the docker file? In other words, if I build the image on apple silicon, can I get a native image?

**Comment by myedibleenso** [comment]
We can definitely publish multi-platform images.  In this case, we'll likely need a different JDK.  

Let's start with this image and we can add others as needed.

**Comment by adarshp** [comment]
Thanks for the cc @enoriega  - at the moment I'm fine with having downstream users build the skema-rs and img2mml images themselves, but will pipe up if that changes.

**Comment by myedibleenso** [comment]
Closed by #223
