### ISSUE TITLE
[swagger] Resolving Ambiguity for CAST LiteralValue vs GroMEt LiteralValue

### ISSUE THREAD

**Issue by titomeister** [ml4ai/skema#171]
Two different instances of LiteralValue currently exist. There is one for CAST and there is one for GroMEt. 
I've recently ran into issues where there is ambiguity as to which LiteralValue is being used when called by its constructor
that is, a call like 
`LiteralValue(...,...)`

Is causing some issues
Currently, there's a temporary fix by changing how the import is done, but a more permanent solution would be nice.
A simple solution would be to change one or both of the LiteralValue names to something different to break ambiguity.

**Comment by myedibleenso** [comment]
Discussed solution: Add prefix to `LiteralValue` for CAST (`CASTLiteralValue`).

**Comment by cl4yton** [comment]
This has been updated in ml4ai/automate-v2/ (directly in master).
- LiteralValue has been renamed as CASTLiteralValue
- Added note to doc string explaining that without different name, swagger codegen code results in name clash between CAST and GrometFN versions of LiteralValue.
