### ISSUE TITLE
[fortran] Integrating new compiler directives and `tree-sitter` CAST

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#186]
After #185 , we need integrate these new directives with our `tree-sitter` CAST.

**Comment by cl4yton** [comment]
Now using this strategy to address #185 :
- using the gcc pre-processor to process compiler directives
- pre-processor produces updated source code that can be sent directly to `tree-sitter`
So there is not any additional work to be done, and issue #185 will include adding to the `tree-sitter`-to-CAST integration.
