### ISSUE TITLE
[GroMEt JSON] Missing GroMEt FN v0.1.6 JSONs

### ISSUE THREAD

**Issue by titomeister** [ml4ai/skema#192]
Some GroMEt JSON files are missing the Google Drive for the following:
- [x] [Some Python examples (10 examples) ](https://drive.google.com/drive/folders/1bi7k4XKgrhbJjPOgSFWGxqRvLNwdqaq1?usp=share_link)
- [x] [Epidemiology models ](https://drive.google.com/drive/folders/1RpM7aqadxjvOTlzgK9FtFOVw6qlWdVao?usp=share_link)

**Comment by cl4yton** [comment]
Done!

There are a couple of Python examples that are not yet generated b/c the examples themselves are works in progress:
- recurse1.py
- recurse2.py
- fun_nested_def.py
