### ISSUE TITLE
[Epi Models] Add additional epi models to gdrive for development

### ISSUE THREAD

**Issue by cl4yton** [ml4ai/skema#193]
Add to the Google Drive additional epidemiology models
- [x] Add MITRE epi starter kit model: https://wiki.codev.mitre.org/display/ASKEM/Models
- [x] Add SIDHARTHE, SIDHARTHE-V, SIDHARTHE-broken

**Comment by myedibleenso** [comment]
Nearly complete (per @cl4yton on 6/9/2023)

**Comment by myedibleenso** [comment]
Update 6/13/2023: still need to upload SIDHARTHE models.

**Comment by cl4yton** [comment]
6/17/2023: SIDARTHE models have been added.
