### ISSUE TITLE
[skema system definition] Add project definition dependencies

### ISSUE THREAD

**Issue by cl4yton** [ml4ai/skema#196]
Adding explicit dependencies for Code2FN components. General question of how best to bookkeep / enforce dependencies. In project.toml?

- [ ] Code2FN dependency on gcc and gfortran (for pre-processor)
- [ ] tree-sitter (for building tree-sitter Fortran grammar) ; Vincent currently has script that clones and builds

**Comment by adarshp** [comment]
`pyproject.toml` is good for enforcing Python package dependencies, but I don't think it handles enforcing things like gcc and gfortran. [Bazel](https://bazel.build) is an industrial strength solution that should be able to handle this, but it's pretty complex and I haven't used it before.

**Comment by myedibleenso** [comment]
This is now addressed in both our [Dockerfile.skema-py](https://github.com/ml4ai/skema/blob/a00595ffba35b8e525794e6a0593461db6420834/Dockerfile.skema-py) (for docker builds) and in our [dev environment instructions](https://ml4ai.github.io/skema/dev/env/).  

Is that sufficient?

**Comment by adarshp** [comment]
@myedibleenso  - I think so.
