### ISSUE TITLE
[python] Bug in ingesting python lotka-volterra implementation

### ISSUE THREAD

**Issue by cl4yton** [ml4ai/skema#197]
Currently Python2CAST breaks when ingesting this file:
https://github.com/smkalami/lotka-volterra-in-python/blob/b126ef16c1c072847dc5fbc9c3afaa549e6d49b1/app.py#L42-L43

- for-loop on lines 42-43
- looks like it might be b/c they have a user-define function 'next' that may be clashing.

**Comment by myedibleenso** [comment]
## TODO

- [ ] turn ingest of this file into a unit test

**Comment by myedibleenso** [comment]
Status update 5/26

- Potential name clash with `next`.  If we're not already adding an internal prefix/suffix, should we do so to help reduce name clashes?

**Comment by titomeister** [comment]
Update 08/18/2023
- Double checked a simplified version of the file that holds the problem code. The output GroMEt looks more consistent now, though I need to do one last check to make sure that the correct function is being called when there is a name clash. After that I will turn this into a unit test and make a PR.
