### ISSUE TITLE
[python] Verify support for recursion idiom

### ISSUE THREAD

**Issue by cl4yton** [ml4ai/skema#199]
Verify whether current function calling supports recursive function calls. 
Two examples that exercise this:
- recurse1.py
- recurse2.py

If not working, then add support.

**Comment by myedibleenso** [comment]
This is a nice test case for understanding support for recursion in GroMet.

As a first step, let's add a unit test to generate a function network from a code snippet containing a recursive function call.


## Notes

- Joseph: Do we want to treat tail recursion differently than other cases when generating the network (ex. tail recursive calls in Python)?

**Comment by myedibleenso** [comment]
Status update 5/26

- recursive piece looks ok (per Tito)
- some output ports missing names
- wire index off by 1

**Comment by myedibleenso** [comment]
Per @titomeister , fixes related to #190 may address the issues @vincentraymond-ua reported.
