### ISSUE TITLE
[fortran] - Add support for Record idiom

### ISSUE THREAD

**Issue by vincentraymond-ua** [ml4ai/skema#205]
The Record idiom occurs in many of the examples space weather files and is already supported by the Python ingestion pipeline, so it is a high priority target for Fortran ingestion as well.

In Fortran, this idiom shows up in two separate ways.
1. module/contains - Fortran OOP equivalent
2. type - Similar to C structs

Will add more details and divide this up into smaller tasks in future sprint

**Comment by myedibleenso** [comment]
## TODO

- Fortran record examples (should mirror or resemble Python record examples)

**Comment by myedibleenso** [comment]
Completed during the hackathon.
