### ISSUE TITLE
Extend Gromet 0.1.6 schema to support automatic ingestion 

### ISSUE THREAD

**Issue by vincentraymond-ua** [ml4ai/skema#208]
Currently, whenever the Gromet schema is updated, the JSON2GroMEt [ingester ](https://github.com/ml4ai/skema/blob/main/skema/program_analysis/JSON2GroMEt/json2gromet.py )needs to be manually updated as well. This causes the ingester to lag slightly behind the current Gromet version. 

I have created a [new version](https://github.com/ml4ai/skema/blob/vraymond/json2gromet_extension/skema/program_analysis/JSON2GroMEt/json2gromet2.py) of JSON2GroMEt that reads the model files directly and does not need to be updated when the schema changes.

However, due to limitations of the current Gromet schema, it is not as efficient, especially with large models. To support efficient ingestion, we would need each data-model class to have a field representing its type name. For example:

`GrometBoxFunction.type_name = "GrometBoxFunction"`

**Comment by vincentraymond-ua** [comment]
For more details, this is because of an ambiguity when reading the Gromet JSON.  


```JSON
{
    "schema": "FN",
    "schema_version": "0.1.6",
    "name": "fun1",
    "modules": ["..."],
    "module_index": [
            "fun1"
     ],
    "executables": ["..."]
}
```

Looking at a snippet from the fun1.py Gromet, there is no easy way to tell what data-model class this represents. By looking at the fields and comparing them to the data-model, we know this is a GrometFNModuleCollection. However, the overhead of doing this adds up, and may break down if we have two classes with the same fields. 

Adding an additional field would remove this ambiguity:
{
    "schema": "FN",
    "schema_version": "0.1.6",
    "name": "fun1",
    "modules": ["..."],
    "module_index": [
            "fun1"
     ],
    "executables": ["..."],
    "type_name": "GrometFNModuleCollection"
}

**Comment by myedibleenso** [comment]
This will mean incrementing to v0.1.7.

**Comment by myedibleenso** [comment]
Per our discussion on 6/2/2023, the implementation will follow that used in CAST (type assignment).

**Comment by enoriega** [comment]
Is there already a timeline for the release of v0.1.7?

**Comment by myedibleenso** [comment]
@enoriega , we're planning to release v0.1.7 by 6/16/2023, but this will differ from 0.1.6 only in that we'll be adding a new field `gromet_type`.  It is an incremental release.

**Comment by enoriega** [comment]
Cool, then this shouldn't be any problem for this issue
