### ISSUE TITLE
[TR] Start web app  in production mode

### ISSUE THREAD

**Issue by enoriega** [ml4ai/skema#209]
Currently, tu run the web app we rely on `sbt`. This is not ideal and makes it complicated to control it within the docker container.
We need to have a a launcher, either bash script or a one-line command to run the web app without `sbt`'s overhead such that it can work as the default command when running the TR docker image

**Comment by enoriega** [comment]
I found a potentially useful pointer at https://www.playframework.com/documentation/2.3.0/Production
Not sure how to install the `activator` command. Seems bundler into play somehow

**Comment by kwalcock** [comment]
I see these two new issues along with "high priority".  My schedule is complicated by some travel.  Can @enoriega give a hint about the time frame?

**Comment by enoriega** [comment]
Done, I started an email thread where we can strategize

**Comment by myedibleenso** [comment]
fwiw, I've bundled Play apps before using SBT Native Packager.  I think the official Play docs recommend this route.

**Comment by kwalcock** [comment]
See #212
