### ISSUE TITLE
[TR] Update Cosmos JSON endpoint on the WebApp

### ISSUE THREAD

**Issue by enoriega** [ml4ai/skema#210]
We have an endpoint that parses cosmos JSON files, where a path to a JSON file is passed as the request's body.

https://github.com/ml4ai/skema/blob/78a1650b03d0f43a27da23327a83561e25913a55/skema/text_reading/text_reading/webapp/app/controllers/HomeController.scala#L287-L298

This end point requires the following enhancements:

- Instead of receiving __a path__ to a JSON file to process, the body should contain __the contents__ of one or more json files. This could be implemented as an array containing the data of each document to annotate as its items
- Update the method name to use camel case instead of snake case.
- Add documentation to the endpoint signature

**Comment by kwalcock** [comment]
@enoriega, where can I find examples of these cosmos json files?

**Comment by enoriega** [comment]
Here are three: [input_examples.zip](https://github.com/ml4ai/skema/files/11643387/input_examples.zip)
Thanks!

**Comment by enoriega** [comment]
Thanks @kwalcock !
