### ISSUE TITLE
[fortran] generate set of examples mirroring Python set

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#217]
Mirroring the set we have for Python, we need to assemble a set of snippets for Fortran.

For each example, we need ...

1. a source file (code snippet)

This will allow us to write unit tests about our expectations around the structure of the networks we generate.

**Comment by vincentraymond-ua** [comment]
Update (6/9/2023) - 
Created Fortran equivalents of:
- exp0-4
- cond1-2
- for1-2
- while1-3
- slice1

Verified that these properly ingest all the way to Gromet.

Additionally, while working through these examples:
1. Fixed support for while loop idiom
2. Added support for Array Literal creation (l = (/ (I, I=1, 10) /)

**Comment by myedibleenso** [comment]
Per our discussion on 6/9/2023, we want to add these examples under `data/gromet/examples` mirroring the structure of Google Drive.  We will not commit Gromet JSON to the ml4ai/skema repo.

**Comment by adarshp** [comment]
>  We will not commit Gromet JSON to the ml4ai/skema repo.

Just wanted to note that we will want to commit certain GroMET JSON files to the repo, namely the ones used for unit testing/continuous integration.
