### ISSUE TITLE
Record idiom not aligning with current CAST schema 

### ISSUE THREAD

**Issue by vincentraymond-ua** [ml4ai/skema#234]
The below code doesn't exactly align with out current CAST schema. The specific issues are:

- We currently interpret both modules and derived types as RecordDefs. In this example, there is a nested RecordDef (module class_Circle, type Circle), which isn't supported by CAST. 
- You can't create an instance of class_Circle, instead you import the module and create an instance of the Circle derived type.
- In this case, there is a one-to-one correspondence between the module and derived type. However, a module could also define zero or multiple derived types. A module doesn't necessarily have to represent a class or object. 
- The functions circle_area and circle_print are defined in the module, but are called on the derived type.

```fortran
module class_Circle
  implicit none
  private
  real :: pi = 3.1415926535897931d0 ! Class-wide private constant

  type, public :: Circle
     real :: radius
   contains
     procedure :: area => circle_area
     procedure :: print => circle_print
  end type Circle
contains
  function circle_area(this) result(area)
    type(Circle), intent(in) :: this
    real :: area
    area = pi * this%radius**2
  end function circle_area

  subroutine circle_print(this)
    type(Circle), intent(in) :: this
    real :: area
    area = this%area()  ! Call the type-bound function
    print *, 'Circle: r = ', this%radius, ' area = ', area
  end subroutine circle_print
end module class_Circle


program circle_test
  use class_Circle
  implicit none

  type(Circle) :: c     ! Declare a variable of type Circle.
  c = Circle(1.5)       ! Use the implicit constructor, radius = 1.5.
  call c%print          ! Call the type-bound subroutine
end program circle_test
```

**Comment by vincentraymond-ua** [comment]
Update 6/16/2023 - During our previous discusses it was decided to treat the module and the program as seperate Modules. In the following, where would the definition of func1 be created?
```fortran
module class_Circle
...
end module class_Circle

program circle_test
...
end program circle_test

function func1(x) !Can be accessed by both the program and the module
     integer, intent(in)  :: x
     func1 = x+1
end function func1
```

**Comment by cl4yton** [comment]
Interesting. Here's how I think it should work -- note that I will need to ask you to verify that this is indeed how Fortran works, but the following is how I think it should be represented in CAST/FN. 

I think there should be *three* modules created in this example:
- class_Circle
- circle_test
- a top-level module that gets the name of file; it is this module that contains func1(x), let's say it was called foo.mat, then the module would be named `foo`.

If either `class_Circle` or `circle_test` refer to an identifier in `foo` (e.g., calling the function `func1` or if Fortran allowed there to be a global constant or even a variable and were to access or set that variable), then either module would import that identifier from `foo` (I suppose this would be an implicit input), just as we explicitly import/use identifiers from other modules.

Does this appear to be consistent with Fortran?

**Comment by vincentraymond-ua** [comment]
To answer your follow-up questions:
If we wanted to import the module into another program, we would do so like:
```fortran
use class_Circle
```
You are only able to import modules or elements of modules in Fortran, so in the above example, you cannot import circle_test.

You never have to use the filename as part of the input because the standard does not allow multiple modules to have the same name. This is not the case with TIE-GCM, but a common convention is to prefix modules with the library name (use lib_module)

**Comment by vincentraymond-ua** [comment]
Resolved a while back. Solution was to allow a single Fortran file to generate multiple CAST/Gromet modules
