### ISSUE TITLE
Docker Jupyter Integration

### ISSUE THREAD

**Issue by jastier** [ml4ai/skema#235]
# Docker Jupyter Integration #

- Add 'pip install jupyter' to the skema-py Dockerfile to allow Jupyter notebooks be launched from within the image. 
- This is a temporary fix for now

Related to: [ Issue #220](https://github.com/ml4ai/skema/issues/220)

**Comment by myedibleenso** [comment]
Resolved by https://github.com/ml4ai/skema/pull/275

See also its use in https://github.com/ml4ai/ASKEM-TA1-DockerVM/blob/1987984791d74d2cb7bb4698cf91612e111f5b06/end-to-end-rest/docker-compose.yml#L6-L17
