### ISSUE TITLE
Wiring bug for gromet FN

### ISSUE THREAD

**Issue by Free-Quarks** [ml4ai/skema#268]
There seems to be a small wiring bug for some gromets in version 0.1.7. Some variables were not wired into their expressions correctly. (perhaps related to USub primitives, but not sure)

Worry about after openhouse though

**Comment by myedibleenso** [comment]
@Free-Quarks , can you please include a link to a gist or a code snippet to reproduce the issue?

**Comment by Free-Quarks** [comment]
When running the following code to generate a gromet https://github.com/ml4ai/skema/blob/main/data/epidemiology/CHIME/CHIME_core_model/code/sir_core.py

The 'beta' in the s_n expression was not wired into rest of the gromet. (it was wired correctly in the i_n expression though)
