### ISSUE TITLE
docker-compose files still needed?

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#282]
Since our service orchestration examples have all moved into https://github.com/ml4ai/ASKEM-TA1-DockerVM , does it make sense to still include and maintain any docker-compose files in this repo?  

If we want to keep them, we'll likely have to update things in two places moving forward.

@adarshp @cl4yton @Free-Quarks @ualiangzhang

**Comment by myedibleenso** [comment]
If removed, we should probably also prune https://github.com/ml4ai/skema/tree/main/notebooks.  Past demos not documented in https://github.com/ml4ai/ASKEM-TA1-DockerVM are available from past code releases.

**Comment by adarshp** [comment]
@myedibleenso - I think we can remove the docker-compose files from this repo, and include a pointer to them in the ASKEM-TA1-DockerVM repo in this repo's top-level `README.md`.

**Comment by myedibleenso** [comment]
Sounds good, @adarshp .  How about those notebooks?

**Comment by adarshp** [comment]
@myedibleenso  - fine with me to move the notebooks as well!
