### ISSUE TITLE
[img2mml] evaluate need for opencv

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#316]
As described in https://github.com/ml4ai/skema/pull/315 , we should reconsider whether opencv is a necessary dependency for this project as its only use currently is this line in `translate.py`:

https://github.com/ml4ai/skema/blob/04fc9d00ea657655556a23091eddc1d78462a630/skema/img2mml/translate.py#L38

We should be able to accomplish that in numpy or torch/torchvision.  OpenCV, though powerful, has a long list of system requirements that end up adding complexity to our builds and bloating our docker images.  If this is all we're doing with opencv, we should consider other options.

**Comment by ualiangzhang** [comment]
@myedibleenso I have made a PR to solve this issue. Thanks!
