### ISSUE TITLE
GroMEt Metadata 0.1.8 Cleanup

### ISSUE THREAD

**Issue by titomeister** [ml4ai/skema#334]
Clay's updated the GroMEt metadata to now include the following two new things
- A 'source_string' field for the CodeFileReference metadata
- Every metadata now includes a field that denotes what type they are (written in lowercase)

After the Hackathon we need to merge these changes into main and resolve anything that gets affected by these changes.

**Comment by myedibleenso** [comment]
@titomeister , has this already been resolved?

**Comment by titomeister** [comment]
On my end I see
- The 'source_string' field for the CodeFileReference metadata
- Every metadata having a field that denotes what type they are.

So I would say that Yes! This has been resolved!
