### ISSUE TITLE
[documentation] REST API examples broken due to two malformed TR endpoint defs

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#345]
Two TR REST endpoint definitions are breaking our OpenAPI docs.

## Problem endpoints
- `/integrated-text-extractions`
- `/integrated-pdf-extractions`

## Steps to reproduce

1. Check out `ghp/data-model-fix`
2. `pip install -e ".[all]"` (I upgraded two deps)
3. Run `uvicorn skema.rest.api:app --host 0.0.0.0 --port 8001 --reload`
4. Open http://localhost:8001/docs#/workflows/equations_to_amr_workflows_latex_equations_to_amr_post and note the example value for the request body <img width="1272" alt="image" src="https://github.com/ml4ai/skema/assets/1137472/7a6c6359-0e2c-4b58-bccd-bb1398cbb224">
5. Uncomment one of the two commented out methods and reload the previous link.  Note the request body example and its link to the data model are now broken.

It took awhile to narrow down the problem this far.  Avoiding the same problem in the future will require adding a unit test for #344 .

**Comment by enoriega** [comment]
Fixed by #349
