### ISSUE TITLE
Missing Port Boxes in EvaluationScenario3

### ISSUE THREAD

**Issue by titomeister** [ml4ai/skema#380]
Justin pointed out a bug that some ports are missing the boxes they belong to.
A specific example of this can be observed in the EvaluationScenario3 GroMEt FN in line 463.

Investigate what's causing this and fix it.

**Comment by myedibleenso** [comment]
## Update 08/08/2023

- @titomeister has identified the root cause

**Comment by titomeister** [comment]
Update 08/11/2023
- I've managed to fix the issue with the ports missing the boxes they belong to. The call handler wasn't appropriately handling how the primitive function generation returns its ports. This caused it to add additional ports (without boxes) when it wasn't necessary. 
- I've spotted some extra wfopi wires that shouldn't be there. I think this has to do with the generation of primitive operators. I'm still investigating this.

**Comment by titomeister** [comment]
Update 08/18/2023
- Fixed an issue involving extra wfopis that shouldn't be there. The main cause was the primitive function handler and its parent function call handler weren't being consistent in how they were creating ports and their respective wires. I've fixed this issue so it's consistent now.
- Doing some last checks and writing in a test file to maintain this, will make a PR tonight.

**Comment by titomeister** [comment]
Update 8/22/2023
- Writing tests to ensure the issue was fixed has unearthed yet another issue with wiring. 
- At this time I don't have a way to consistently solve this issue without breaking something else.

**Comment by myedibleenso** [comment]
## Update for 8/22/2023

- Committing to a partial refactor of function call handlers to address a series of wiring issues
