### ISSUE TITLE
[matlab] Initial support for MATLAB frontend

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#382]
As we begin adding support for MATLAB, we should add unit tests corresponding to idioms found in the SV2AIR3-Waterloo-MATLAB model.

**Comment by jastier** [comment]
- MATLAB grammar and test corpus repos now cloned like the existing fortran repo.
- Shared objects building
- CAST model in progress now

**Comment by myedibleenso** [comment]
@jastier , please add you update for 8/15.

**Comment by jastier** [comment]
- Full build of project during test runs
- MATLAB files now recognized by the file ingesters.  
- Tests now run from the skema root directory.

**Comment by jastier** [comment]
Updates for 8/18/2023
- Tree traversal
- Early module and CAST object

**Comment by jastier** [comment]
Updates for 8/22/2023

- Integrated latest main branch changes.
- CAST adaptation for MATLAB syntax (ongoing).

**Comment by jastier** [comment]
Updates for 8/25/2023

- Assignment from primitive types complete
- GROMET JSON generated

**Comment by jastier** [comment]
Updates for 9/1/2023

- Adding automated tests.  These are used for development and CI.

**Comment by jastier** [comment]
Updates for 9/5/2023

- Continued work on testing

**Comment by jastier** [comment]
Updates for 9/8/2023

Continued expansion of CAST code for MATLAB
- Simple classes are next.  Tree building correctly and parsing completes without errors
- Fixing a bug where CAST object is not generated.

**Comment by jastier** [comment]
Updates for 9/25/2023
- CAST/matlab PR integrated into the main skema branch.  
- We have defined a preliminary MATLAB grammar coverage goal of being able to process the [SV2AIR3-Waterloo](https://artifacts.askem.lum.ai/askem/data/models/zip-archives/SV2AIR3-Waterloo-MATLAB.zip) data model.

Next PR:
- Design a test plan that runs with GitHub CI and can be run locally.  The testing should process a directory of unit tests.  Add a few simple tests to prove the concepts.
