### ISSUE TITLE
Failure in test_integrated_text_reading_proxy.py

### ISSUE THREAD

**Issue by adarshp** [ml4ai/skema#387]
There seems to be an error while trying to connect to COSMOS:

`
skema/rest/tests/test_integrated_text_reading_proxy.py::test_integrated_pdf_extraction - requests.exceptions.ConnectionError: HTTPConnectionPool(host='cosmos0002.chtc.wisc.edu', port=8089): Max retries exceeded with url: /process/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f57924d9520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
`

This is making our integration tests that are part of our pre-main branch merge checks fail every time.

@enoriega  - perhaps we should disable this particular test for CI?

**Comment by jastier** [comment]
Cosmos recently changed their processing URL.   The new one is:  `https://xdd.wisc.edu/cosmos_service/process/`

A port number is no longer specified.

To process a .pdf file:  `curl --form '<your_pdf_file_here>' https://xdd.wisc.edu/cosmos_service/process/`
To check processing status:` curl https://xdd.wisc.edu/cosmos_service/process/<job_id>/status`
To get processing result: `curl https://xdd.wisc.edu/cosmos_service/process/<job_id>/result`

**Comment by enoriega** [comment]
Thanks for pointing this out @jastier

**Comment by jastier** [comment]
No prob, I just had to solve the same problem on our SKEMA code.  In our case, the calling routines add the 'process' suffix, so a direct replacement was:

`"https://xdd.wisc.edu/cosmos_service"`

**Comment by myedibleenso** [comment]
Has this been resolved?

**Comment by enoriega** [comment]
Yes. It was solved. Thanks!
