### ISSUE TITLE
The textreader webapp has a lazy val alignmentHandler that will crash if evaluated

### ISSUE THREAD

**Issue by kwalcock** [ml4ai/skema#389]
The alignmentHandler seems to be intended to support the align endpoint, which is in the routes file, but is not included in api-v1.html.  If the goal is to reduce the memory usage, then we need to do some house cleaning.  We've got three TextReadingPipelines, all of which themselves use a MiraEmbeddingsGrounder plus one more directly created MiraEmbeddingsGrounder.  The plainTextPipeline is for textFileToMentions, but that is not in api-v1.html, either.  Before we go to more extreme measures to share large objects between components, we should remove the components that are not being used.  That can begin by paring down routes to match api-v1.html (keeping the index, resources, etc. what aren't in the api).  I can take it from there.

**Comment by enoriega** [comment]
@kwalcock I agree. Please go ahead if you ara available. I will come back in the 17th

**Comment by kwalcock** [comment]
I meant api-v1.yaml, of course.  I'm going to double check with @myedibleenso about what parts of the API are really being used.  Is this documented or specified anywhere?

**Comment by myedibleenso** [comment]
@kwalcock , I think the best set of footprints to follow are going to be the series of calls in [`skema/rest/integrated_text_reading_proxy.py`](https://github.com/ml4ai/skema/blob/2bdcfac95c5108d67a1c233a49a5a6ba6e77d7f4/skema/rest/integrated_text_reading_proxy.py)

**Comment by kwalcock** [comment]
The alignment handler has been removed as part of the effort to reduce memory footprint.  The related PR is forthcoming.

**Comment by kwalcock** [comment]
#414 should have taken care of most of it.
