### ISSUE TITLE
[tests] Add zip archive of each model to s3 bucket for CI

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#391]

**Comment by vincentraymond-ua** [comment]
@myedibleenso - Do we want these zip archives to be as minimal as possible (i.e. only containing source code) or essentially a copy of what is on Google Drive? 

Many of the models include extraneous files alongside the source such as documentation or data.

**Comment by myedibleenso** [comment]
We had to decided to make "lean" archives only containing source code.

**Comment by vincentraymond-ua** [comment]
I've started uploading these to the Google Drive. They are under `data/models/zip_archives/`

**Comment by myedibleenso** [comment]
The models (code only) are now accessible at the following URLs:

https://artifacts.askem.lum.ai/askem/data/models/zip-archives/CHIME-SIR-model.zip
https://artifacts.askem.lum.ai/askem/data/models/zip-archives/CHIME-SVIIvR-model.zip
https://artifacts.askem.lum.ai/askem/data/models/zip-archives/ABM-COmplexVID-19.zip
https://artifacts.askem.lum.ai/askem/data/models/zip-archives/ABM-COVID-ABS.zip
https://artifacts.askem.lum.ai/askem/data/models/zip-archives/CHIME-penn-full-model.zip
https://artifacts.askem.lum.ai/askem/data/models/zip-archives/MechBayes.zip
https://artifacts.askem.lum.ai/askem/data/models/zip-archives/SIDARTHE.zip
https://artifacts.askem.lum.ai/askem/data/models/zip-archives/Simple-SIR.zip
https://artifacts.askem.lum.ai/askem/data/models/zip-archives/Climlab.zip
https://artifacts.askem.lum.ai/askem/data/models/zip-archives/SV2AIR3-Waterloo-MATLAB.zip
https://artifacts.askem.lum.ai/askem/data/models/zip-archives/Bucky.zip
https://artifacts.askem.lum.ai/askem/data/models/zip-archives/ABM-REINA.zip
https://artifacts.askem.lum.ai/askem/data/models/zip-archives/Cornell-COVID19-sim-Frazier.zip
https://artifacts.askem.lum.ai/askem/data/models/zip-archives/ABM-Covasim.zip
https://artifacts.askem.lum.ai/askem/data/models/zip-archives/TIE-GCM.zip
