### ISSUE TITLE
[code2fn] Investigate execution of Gromet FN

### ISSUE THREAD

**Issue by vincentraymond-ua** [ml4ai/skema#399]
## Update 8/18/2023
Using the source:
```python
a = 1
b = 2 + 3
c = a + 4
d = a + b
e = 1 + 3 + 2
```
We are able to do the following:
- Upload Gromet JSON to Memgraph
- Run cypher query to access the opo representing each left side variable.
- Backtrack through graph, executing along the way, to retrieve initial value.  

Output looks like:
```
{
    'a': tensor(1, dtype=torch.int32),
    'b': tensor(5, dtype=torch.int32), 
    'c': None, 
    'd': None, 
    'e': tensor(6, dtype=torch.int32)
}
```
Discovered some issues with Memgraph wiring, passed off to @Free-Quarks  to look into. That is why c and d show up as None above.

**Comment by vincentraymond-ua** [comment]
Link to code on branch: https://github.com/ml4ai/skema/tree/6c7a9f0fdcb7903635bcde2ee13de8176a8c4d16/skema/gromet/execution_engine

**Comment by Free-Quarks** [comment]
Thanks for tracking this here! I had it a google doc under my todo's but having it here is better!

**Comment by vincentraymond-ua** [comment]
## Update 8/22/2023

In our meeting last week, we discussed wanted to call the torch operators rather than vanilla Python operators. After further research, I realized that we are actually calling the torch operators under the hood. This is because Tensor overrides the basic Python operators. So:

`operator.add(tensor_a, tensor_b)` == `tensor_a  + tensor_b` == `torch.add(tensor_a, tensor_b)`

**Comment by myedibleenso** [comment]
@myedibleenso , it seems that this approach has legs.  For planning purposes, it would be helpful to create a series of issues that each cover a piece of the EE.

**Comment by myedibleenso** [comment]
@vincentraymond-ua , once we have those other issues, I think we can safely close this one.
