### ISSUE TITLE
[MORAE] - Wiring bugs in Memgraph

### ISSUE THREAD

**Issue by vincentraymond-ua** [ml4ai/skema#400]
There a couple of wiring bugs when converting from Gromet JSON to the Memgraph graph representation. 

## Missing primitive WFOPI
When a primitive operator has an opi as an input (x=1+y) the wire from the primitive to the opi is missing.

## Missing function input wires
When user defined functions are called, their inputs are not correctly wired to the opi. 

## Missing index field on wires causing ambiguity
There are some cases where wires don't have index fields, but should have them to avoid ambiguity. In the following example there are 4 ast.Div :Primitive nodes that are all children of a top level :Expression node. Since there is not an index field, we don't know which primitive to start with. 
```Python
output = a/b/c/d/e
```

## Builtin functions not showing up in memgraph
Calls to builtin functions like `print()` and `min()` are not showing up in the memgraph database.

## Mysterious user defined function bug
There is a werid bug that causes the memgraph import to crash if a user defined function takes no input and is called more than once. I've confirmed that both of these things have to be true for the crash to occur. 
```Python
def foo():
    return 1+2
out = foo()
out_2 = foo()
```

**Comment by vincentraymond-ua** [comment]
## Update 9/5/2023
Added additional wiring bug

**Comment by vincentraymond-ua** [comment]
## Update 9/8/2023
Updated issue regarding missing function input wires to generalize it to all user defined function calls.

**Comment by Free-Quarks** [comment]
@vincentraymond-ua I am going through some older issues that are still open and closing some of them out. 

I think I have fixed these bugs for now. At least to my knowledge. Does that seem correct to you too?

**Comment by Free-Quarks** [comment]
I think this was fixed at some point, not sure when though
