### ISSUE TITLE
Issue with artifactory instance

### ISSUE THREAD

**Issue by adarshp** [ml4ai/skema#41]
Hi @kwalcock - we are getting some CI build errors that look related to your artifactory instance. Do you know what might be going on? I've attached the error log.

[logs_ml4ai_skema_189_2_2.log](https://github.com/ml4ai/skema/files/10173272/logs_ml4ai_skema_189_2_2.log)

**Comment by enoriega** [comment]
@adarshp there is a scheduled power outage at GS which is affecting all hosted services. Including artifactory.

**Comment by kwalcock** [comment]
@enoriega, I haven't received an all clear yet or any news, but it looks like the machine in question did not go down.  artifactory, aheadaz, elasticsearch, etc. are still running and the machine didn't reboot.  I'm looking at the log next.

**Comment by kwalcock** [comment]
I deleted the file in question on my computer and reran sbt without it complaining.  The checksum matched both before and after.  Do you have a way of manually running sha1sum on the file

`/root/.cache/coursier/v1/http/artifactory.cs.arizona.edu%3A8081/artifactory/sbt-release/org/clulab/model-streamed-trigram-ser_2.12/1.0.0/model-streamed-trigram-ser_2.12-1.0.0.jar`?

The file should have 2,239,559,276 bytes and it is reported to have been downloaded 209 times from [http://artifactory.cs.arizona.edu:8081/artifactory/webapp/#/artifacts/browse/tree/General/sbt-release-local/org/clulab/model-streamed-trigram-ser_2.12/1.0.0/model-streamed-trigram-ser_2.12-1.0.0.jar](artifactory).

I don't know what might have gone wrong except a temporary outage or maybe a limit imposed on file sizes at some point in the process on the CI server.

**Comment by adarshp** [comment]
@kwalcock, @enoriega  - thanks for looking into it! 

@kwalcock  - there is probably a way to manually run sha1sum on that file, but I don't know how to do it off the top of my head. For now I'll leave it be, but if the issue persists, I can take a stab at it.

**Comment by cl4yton** [comment]
@adarshp and @kwalcock : What is the status of this issue? If no longer relevant, close?
