### ISSUE TITLE
[fortan] Investigate and support Fixed-Form Fortran code

### ISSUE THREAD

**Issue by vincentraymond-ua** [ml4ai/skema#411]
Currently we've been targeting Free-Form Fortran code and the Fixed-Form idioms that appear in the TIE-GCM model. We should investigate:

- Which Fixed-Form idioms is tree-sitter not able to parse?
- Can we use a tool like [fixed2free ](https://github.com/ylikx/fortran-legacy-tools) as a preprocessing step to convert Fixed-Form code to Free-Form automatically?
- If not fixed2free, can we add additional step(s) to the preprocessor to convert these idioms into a form supported by tree-sitter-fortran like how we've done with continuation lines?

**Comment by vincentraymond-ua** [comment]
## Updated 8/29/2023
Investigated using fixed2free.py to support Fixed-Form Fortran ingestion with TIE-GCM model.  This resolves ~90% of Fixed-Form cases in TIE-GCM. However, there are a couple limitations:

- Will break if run on non Fixed-Form source. For TIE-GCM at least, you can tell by the file extension (.F = Fixed-Form, .f90 = Free-Form)
- Does not support Tab-Form lines, which show up in a few instances. 

Additionally, this has also identified a couple of unrelated issues with TIE-GCM support:

- Computed GO TO statement  `GO TO (10, 20, 30), VAR`. To be resolved by [this](https://github.com/stadelmanma/tree-sitter-fortran/pull/87) PR.
- Assignment to keyword. Keywords are not reserved words in Fortran. However, tree-sitter-fortran does not support this.

**Comment by myedibleenso** [comment]
It looks like each frontend will have a preprocessor.  It's unclear if preprocessing steps can be statically determined or if different orders will be necessary at different times.

**Comment by vincentraymond-ua** [comment]
## Update 9/5/2023

Set aside for a little bit to focus on MORAE/execution engine work

**Comment by vincentraymond-ua** [comment]
## Update 9/8/2023

I ended up being able to find time to work on this. I have implemented fixed2free into the Fortran preprecessor like we discussed previously. 

Here is current status of the issues:

### Breaking on non fixed-form source files
Resolved, we run tree-sitter on the initial source file to check if it parses correctly, then run fixed2free if it does not. This replaces our previous continuation line preprocessing step. 

### Does not support tab lines
Still investigating. The GCC preprocessor converts tabs to spaces, but fixed2free has to be run after GCC to parse any files that may have been included. 

### COMPUTED GOTO
Resolved, this support was added by tree-sitter-fortran

### Assignment to keyword
Not as large of an issue as previously thought. It seems like this issue is specific to the FORMAT keyword. And even then it only occurs if format is on the left side of an assignment. 

Should have PR ready by next Thursday for end of sprint.

**Comment by vincentraymond-ua** [comment]
## Update 9/12/2023

Finished support for tab-lines. Working on unit tests for testing TIE-GCM parsing support.

**Comment by vincentraymond-ua** [comment]
## Update 9/15/2023

To be resolved by #479
