### ISSUE TITLE
[MORAE] Refactor database.rs

### ISSUE THREAD

**Issue by Free-Quarks** [ml4ai/skema#417]
This is the primary file for converting FN's into the Cypher graph representation. It's become quite disorganized as adding support to new gromet spec's has been done in a patchy way. It needs a good refactoring. (It is also very inefficiently written in Rust and can use some cleanup in that regard as well)

**Comment by Free-Quarks** [comment]
Still working on the refactor. To my own dismay, I did not keep up to date with the documentation for this codebase as it was updated, so I have been working on new documentation and tracking of the refactor here: https://docs.google.com/document/d/1bjUjwq8AiK6Oee5Y76rrQSYMZb3rTr13lRzVT3wv3Zs/edit?usp=sharing

This is a slow building momentum type thing but I am finally getting some momentum!

I have also collected a list of function networks that would make a good test for the refactor, once I get to the testing point.

**Comment by Free-Quarks** [comment]
Bulk of initial refactor is done. Debugging the wires is taking longer than expected though, but no blockers.

**Comment by Free-Quarks** [comment]
This is still progressing. working through wiring bugs and updating features to current specs still. It's not really that it's taking more work than I planned, but I just have been struggling to carve out good chunks of time to work on it, so it's taking longer because of that.

**Comment by myedibleenso** [comment]
@Free-Quarks , let's aim to wrap up the _refactor_ by Friday (9/22).

**Comment by Free-Quarks** [comment]
Conditionals and while loops no longer cause crashes, at least to the degree I have tested. I think I have addressed some of the wiring bugs Vincent brought up and the wiring for simple examples seem to be correct too. 

Wiring for loops and conditionals is still bugged though, and I haven't thoroughly tested more complicated function nets yet either.

**Comment by Free-Quarks** [comment]
Started up branch 2 for this to continue working on this. 

Done this week:
- Debugged a couple wiring issues
- Added preliminary support for for loops

To be done still:
- Fix wiring for loops and conditionals
- Further testing and debugging

**Comment by Free-Quarks** [comment]
Current state on the remaining stuff for refactoring is:

- [ ] #555  
- [ ] #556 
- [ ] #547 
- [ ] clean up code to clippy levels
