### ISSUE TITLE
[execution engine] Endpoint for AMR enrichment

### ISSUE THREAD

**Issue by vincentraymond-ua** [ml4ai/skema#423]
The execution engine should be able to accept an AMR as input, enrich it with extracted parameter values, and then return the new AMR as output. We then want to turn this pipeline into a REST endpoint.

- [ ] Accept AMR as input and pull out filename and parameters.
- [ ] Run parameter extraction over each parameter and update AMR.
- [ ] Create REST endpoint for this pipeline.

**Comment by vincentraymond-ua** [comment]
## Update 9/5/2023
Currently awaiting updates to amr generation pipeline to begin work on AMR enrichment.

**Comment by vincentraymond-ua** [comment]
## Update 9/8/2023

Initial scaffolding in place for endpoint, still awaiting updates to AMR generation.

**Comment by vincentraymond-ua** [comment]
## Update 9/12/2023

Still on the backburner temporarily awaiting updates to AMR generation.

**Comment by myedibleenso** [comment]
@vincentraymond-ua , can you update the status for this one?

**Comment by vincentraymond-ua** [comment]
Resolved as of #608
