### ISSUE TITLE
[gromet] - Python multiline comments converted to List LiteralValue

### ISSUE THREAD

**Issue by vincentraymond-ua** [ml4ai/skema#434]
Python multiline comments are being converted to a List Literal Value in Gromet. The list contains a single string representing the comment. This isn't a major issue, but is causing confusion in the execution engine. I think since comments are now being included in Metadata, we should remove this.

For an example, see the following Gist:
https://gist.github.com/vincentraymond-ua/095e50f5e2217e52c6d863a2bc149916

**Comment by myedibleenso** [comment]
## Short-term plan

Remove ML comment (treated as a string) from the AST; revisit when migrating to a tree-sitter-based frontend for Python.

**Comment by titomeister** [comment]
Update 9/15/2023 
- I've removed multi-line comments from the AST.
- This change will come in with the Function Call Handler PR.
