### ISSUE TITLE
[Text Reading] Timeout errors for tests involving COSMOS

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#441]
We're encountering timeout errors with text reading tests involving calls to COSMOS:

```
FAILED skema/rest/tests/test_integrated_text_reading_proxy.py::test_integrated_pdf_extraction - TimeoutError: Timed out waiting for COSMOS on retry num 200
FAILED skema/rest/tests/test_integrated_text_reading_proxy.py::test_cosmos - TimeoutError: Timed out waiting for COSMOS on retry num 200
```

**Comment by enoriega** [comment]
The culprit is the COSMOS service, it is too slow processing the PDF that our code is timing out. I commented out two unit tests that call it to unblock the CI flow, but won't close this issue until I mock the COSMOS endpoint to allow our tests stop relying on an external service.
