### ISSUE TITLE
[MORAE] cleaning mathml for Image2AMR endpoint

### ISSUE THREAD

**Issue by Free-Quarks** [ml4ai/skema#457]
The image2amr endpoint (`/images/base64/equations-to-amr`) is crashing and I think it's just because the mathml from it is not being cleaned as is done for the LaTeX2amr endpoint mathml. So we need to use that `clean_mml` util on the image endpoint as well.

**Comment by myedibleenso** [comment]
See https://github.com/ml4ai/skema/blob/63c52ef790825f8add7c7ff2c51fba60ebd4ead6/skema/rest/utils.py

**Comment by Free-Quarks** [comment]
I implemented this as a tag along with Deepsana's most recent PR
