### ISSUE TITLE
[code2FN] Adding support for GOTO

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#461]
In working through #411 , @vincentraymond-ua identified cases of GOTO and computed GOTO.  Currently, CAST (and by extension GROMET) supports neither idiom. 

How should this be approached?  It seems sensible to focus on the concrete use case of TIE-GCM when considering how best to represent these idioms.

**Comment by vincentraymond-ua** [comment]
Resolved by #775  and #780
