### ISSUE TITLE
`/metal/link_amr` returns `500`

### ISSUE THREAD

**Issue by brandomr** [ml4ai/skema#475]
Yesterday I had no issue sending [these extractions](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/tests/scenarios/basic/extractions.json) and this [AMR](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/tests/scenarios/basic/amr.json) and receiving an enriched AMR. Today though I'm bumping into a `internal server error` 500 response with the exact same submission (both content + request code).

**Comment by enoriega** [comment]
@brandomr I verified and the service works well, but the file format is outdated.  I regenerated the extractions file and opened https://github.com/DARPA-ASKEM/knowledge-middleware/pull/53
