### ISSUE TITLE
[TextReading] Play! Web Service resets connection with client for long inputs

### ISSUE THREAD

**Issue by enoriega** [ml4ai/skema#476]
## Problem

The [cosmosJsonToMentions](https://github.com/ml4ai/skema/blob/df1f8066245452bf7313d6e78595b7399ca862df/skema/text_reading/scala/webapp/app/controllers/HomeController.scala#L86) endpoint on the Play! REST api is blocking and times out for long papers, such as the SIDARTHE. 

Upon debugging I discovered that the underlying server process handling the request closes the connection even if the controller method runs to completion after the request is left orphaned.

I attach the cosmos json input that replicates this issue
[sidarthe.zip](https://github.com/ml4ai/skema/files/12603213/sidarthe.zip)

**Comment by enoriega** [comment]
@myedibleenso FYI. The issue is on the server process of the scala code, not on the fastapi client code

**Comment by kwalcock** [comment]
I saw this.  There's probably a timeout setting somewhere that I can change.

**Comment by enoriega** [comment]
I spent a bit of time trying to find where to find it but failed 😞

**Comment by myedibleenso** [comment]
I think there are three settings you may need to alter:


```text
play.server.akka.requestTimeout=infinite"
play.server.akka.terminationTimeout="10 seconds"
play.server.http.idleTimeout="2400 seconds"
```

**Comment by myedibleenso** [comment]
^adjust those values as you feel makes sense
