### ISSUE TITLE
Use of container_box

### ISSUE THREAD

**Issue by kwalcock** [ml4ai/skema#50]
This isn't really an issue, but the links work better here.

@enoriega,

In the code below it looks like the `container_box` is set to different values in the b-loop and then left on its last value for the next opi-loop and the rest.  Does that last container_box have some special significance to the opi's?

https://github.com/ml4ai/skema/blob/b5a1de41e3f576b68da5121f1d90195f0cd930bc/skema/text_reading/mention_linking/gromet_linker/align_comments.py#L201-L213

**Comment by enoriega** [comment]
@kwalcock I am not 100% sure, but I think that yes, a "box" is a container with ports (like opi and pof), so the box's container  is itself and the ports' containers is the current box.

**Comment by kwalcock** [comment]
I had missed the comment in the yaml that `b: The FN Outer Box (although not enforced, there is always only 1).`.
