### ISSUE TITLE
Do we support * for eq2amr?

### ISSUE THREAD

**Issue by Free-Quarks** [ml4ai/skema#512]
In some debugging inputs from other teams I noticed we are getting parsing errors when we take in LaTeX which has explicit multiplications, `*`

For example the following will crash on the multiplication sign `*`

```
{
  "equations": [
    "\\frac{d S}{dt}=-N\\beta I S",
    "\\frac{d I( t )}{dt}=r_{EI}E - p_{IH}r_{IH}I - p_{IR}r_{IR}I",
    "\\frac{d R( t )}{dt}=p_{HR}r_{HR}H+p_{IR}r_{IR}I",
    "\\frac{d H( t )}{dt}=p_{IH}r_{IH}I-p_{HD}r_{HD}H-p_{HR}r_{HR}H",
    "\\frac{d E( t )}{dt}=-r_{EI}E+N\\beta I S",
    "\\frac{d D( t )}{dt}=p_{HD}*r_{HD}*H"
  ],
  "model": "petrinet"
}
```

It seems like uncharted is working on automating the generation of latex and are including the `*`, so we should probably support them, also their unicode: &#x2217;

**Comment by adarshp** [comment]
We don't support it yet, but it shouldn't be difficult to do so. Perhaps @deepsana can take a crack at it

**Comment by Free-Quarks** [comment]
Sounds good! 

Also the unescaped unicode is the following with no spaces: & # x 2 2 1 7 ;
