### ISSUE TITLE
Make the labels consistent, between relation, event and with the correct casing

### ISSUE THREAD

**Issue by enoriega** [ml4ai/skema#52]
Some of the events have the same label with different casing. This makes them inconsistent. This should be fixed probably at the grammars

**Comment by enoriega** [comment]
I don't think adding due dates supported in GitHub issues. But for the record: Due date is `03/28/23`

**Comment by myedibleenso** [comment]
@enoriega , what is the status of this issue?

**Comment by enoriega** [comment]
Still in my TODO

**Comment by enoriega** [comment]
Update on this: There are cases where a mention is a relation with the same label (i.e. a `ParameterDescription`) because the rule didn't have a trigger. This explains the inconsistency with the mention type.

Still to fix the casing inconsistency

**Comment by enoriega** [comment]
There are two concerns described in the PR:

1. The inconsistency between `relation` and `event`. This is an artifact of how the odin engine works, so it is not a bug, therefore won't be "fixed"
2. Label casing: I remember seen an instance of an event with a lowercased label. I haven't been able to reproduce and can't find it, so I will stop hunting it for now, as this is not pressing. I will keep an eye on this, though. If I encounter it in the future I will reopen this Issue.
