### ISSUE TITLE
[morae] Further improvements to LiteralValue representation

### ISSUE THREAD

**Issue by vincentraymond-ua** [ml4ai/skema#528]
Upon further execution_engine work, there are a few more improvements to the Gromet LiteralValue representation I think we could make.

1. Have strings represented as String type instead of List type. See [here](https://mlbayes.slack.com/archives/CF1S834KH/p1695934231057919) for current discussion.
2. Fix inconsistent use of quote characters in LiteralValue.value field
3. Fix Gromet representation of Tuple LiteralValue. 
4. Improve List representation in Memgraph. Currently Lists are represented as a long literal string like:
```
"[{"value_type":"Integer","value":1,"source_code_data_type":["Python","3.8","<class 'int'>"],"source_refs":[{"source_file_name":"literal_test","col_start":8,"col_end":9,"row_start":7,"row_end":7}]},{"value_type":"Integer","value":2,"source_code_data_type":["Python","3.8","<class 'int'>"],"source_refs":[{"source_file_name":"literal_test","col_start":10,"col_end":11,"row_start":7,"row_end":7}]},{"value_type":"Integer","value":3,"source_code_data_type":["Python","3.8","<class 'int'>"],"source_refs":[{"source_file_name":"literal_test","col_start":12,"col_end":13,"row_start":7,"row_end":7}]}]"
```
Creating a Tensor for this is complex. Our current strategy is to literally evaluate this string with ast.literal_eval, create dummy Memgraph nodes for each element, and then visit each dummy node. Perhaps  we could have a top level List LiteralValue node, and then children Nodes for each LiteralValue element connected by a :Contains relationship.

**Comment by Free-Quarks** [comment]
This is a duplicate issue that didn't get closed earlier
