### ISSUE TITLE
[code2FN] Certain plotting boxes don't have a function_type field

### ISSUE THREAD

**Issue by Free-Quarks** [ml4ai/skema#537]
I noticed some boxes related to plotting seem to be missing a function_type field in the FN. I believe this is a bug. 

the json: https://gist.github.com/Free-Quarks/e63b6aff1c61a90010cd18fb5d3453fe#file-sidarthe_full-json

the code: https://gist.github.com/Free-Quarks/e63b6aff1c61a90010cd18fb5d3453fe#file-sidarthe_full-py

**Comment by titomeister** [comment]
Update 10/13 
- I've found the issue and have fixed it.
- Created a draft PR for merging the fix in, would like to add some kind of test before I convert to normal PR.
