### ISSUE TITLE
It would be useful to have line numbers for docstrings

### ISSUE THREAD

**Issue by kwalcock** [ml4ai/skema#54]
Aside from it just not being efficient to throw information away, not having line numbers for docstrings but having them for comments necessitates handling the two differently in code.  It would be great to have access to the docstring line numbers in the files with extracted comments.

**Comment by adarshp** [comment]
@kwalcock - docstrings span multiple lines - would you like just the starting line number, start and end line numbers, or line numbers for each line of the docstring? Even better, if you can provide an example JSON fragment with your preferred format, it will help speed up development.

**Comment by kwalcock** [comment]
Whatever is easiest.  If it's all the same, then something like this below would work fine.  I'm a little concerned that method overloading is not taken into account.  `get_beta` might not be unique.

```json
	"docstrings": {
		"get_beta": {
                    "line_begin": 1,
                    "strings": [
		        "",
		        "    Calculates a rate of exposure given an intrinsic growth rate for COVID-19",
```

**Comment by adarshp** [comment]
@kwalcock Thanks for providing the example! We'll try to match it if possible.

Re: method overloading - good point. I haven't encountered method overloading in Python so far, so it wasn't on my radar. Perhaps we should return a list of 2-tuples of (function name, docstring), instead of a dictionary? Would that work for you?

**Comment by kwalcock** [comment]
Right.  Python doesn't have function/method overloading and it looks like Fortran uses different names for the methods.  Probably we'll never come across it and I'm not sure I should encourage future proofing.  However, Python does have classes and what would happen if two classes had methods of the same name?  That happens often in code, but perhaps not code related to published papers where it might have been simplified and made procedural.  If there needs to be a string for the function, an int for line number, and array of strings for the docstrings, I would favor a dictionary over a tuple.  Does Open API handle tuples at all?  (Apparently it does by using lists of fixed sizes.)  Perhaps the class or module needs to be added in the future to distinguish duplicates so that the tuple becomes unwieldy.  Do the syntax trees not include comments so that comment extraction needs to be done separately like this?

**Comment by adarshp** [comment]
@kwalcock  - @jastier  is working on handling the case where there are two classes with methods of the same name. Basically, we were thinking there would be keys in the dictionary like `"classA.methodA"`, `"classB.methodA"`. 

However, from looking a bit online, It does look like docstrings are included in the AST. I think given that, perhaps it's best for the program analysis folks to provide the docstrings along with the GroMEt JSON file, and reserve the comment extraction module for non-docstring comments, which are not preserved in the AST. How does that sound?

**Comment by adarshp** [comment]
@kwalcock  - Just talked to @vincentraymond-ua  - he reports that including the docstrings in the GroMEt JSON output caused some downstream issues in the past with CAST/GroMEt generation, so they had to remove them from code modules. Let me think about this issue a bit more and get back to you.

**Comment by kwalcock** [comment]
It sounds reasonable to try to extract just once.  I'm just guessing, though, not having the big picture (as you just pointed out).

**Comment by adarshp** [comment]
@kwalcock  - I may have spoken too soon. @titomeister reports that the GroMEt JSON does contain the docstrings after all. From his Slack message: 

> "Currently docstrings will appear in the GroMEt JSON as LiteralValues representing strings. This is because in the Python AST they show up as strings and don’t get filtered out like regular Python # comments. Like Vincent said they’ve given use some issues in the past in specific cases, but in general they should appear correctly now unless there’s some weird edge case I’m not aware of.
> 
> In regards to the github issue since they show up in the AST we should already have line number information for them as well, since the Python AST provides line number information for free."

Will that work for you? If so, let me know, and I'll do the following:

1. Close issues #31 and #54
2. Remove the existing Python docstring extraction functionality from the comment extractor.
