### ISSUE TITLE
[MORAE] handling if __main__:

### ISSUE THREAD

**Issue by Free-Quarks** [ml4ai/skema#587]
`if __main__:` statements in the code are tricking the FN -> memgraph code into thinking it's a non executable file and initiating the library walker to traverse the FN, after that walk it still constructs conditionals and loops, but this is causing a double walk of the FN because that conditional is connected to everything.

**Comment by Free-Quarks** [comment]
@titomeister Are all conditional and loops put at the top of the FN? Or if a function had a conditional inside it the `bc` would be inside that function box and not at the top level of the FN?

**Comment by Free-Quarks** [comment]
Awesome! Thanks Tito! So my check on if it's a library file and not like an executable script should be if it has no `bf`'s or `bc`'s or `bl`'s at the top level.

**Comment by titomeister** [comment]
Oh yeah, if you're trying to look for something like the `if __main__:` statement that would probably be a good way to start.
Would it make sense to also have some kind of check to find a call to a `main()` since that's another way to 'execute' Python code?

**Comment by Free-Quarks** [comment]
If there is a `bc` at the top and nothing in the `bf` it has to be a `if __main__:` or I guess an `if environment_variable:` but both would be an entry point to execution, so I think just checking for a `bc` at top should be good enough. Does that make sense / sound reasonable?
