### ISSUE TITLE
[code2fn] - Gromet pipeline changing current working directory 

### ISSUE THREAD

**Issue by vincentraymond-ua** [ml4ai/skema#596]
During the Gromet pipeline, the cwd is changed multiple times. Normally, the cwd is changed back once Gromet is generated. However, if the Gromet pipeline fails and the exception is caught, the cwd is  never changed back. This causes unexpected behavior and depending on where the pipeline failed and where the script was originally run from, the cwd can be completely different.

This makes writing scripts like the model_coverage_report more complicated as you have to assume that the cwd has been changed and change it back before/after every step.

**Comment by vincentraymond-ua** [comment]
Need to look in to where the Gromet pipeline is changing the cwd.

**Comment by titomeister** [comment]
@vincentraymond-ua Was this resolved or is this still ongoing?

**Comment by vincentraymond-ua** [comment]
Yes, this is resolved, I'll go ahead and close it out.
