### ISSUE TITLE
[code2FN] Tree-Sitter to CAST Missing Identifiers

### ISSUE THREAD

**Issue by titomeister** [ml4ai/skema#740]
The Python Tree-Sitter to CAST implementation is missing identifiers for certain elements.
In particular, the very first line of the source file will have its identifiers missing.

We're thinking it's a bug with the `get_identifier()` function in `node_helper.py`. Something is off about the indexing.
When we add an additional blank line at the top of the source file, then we get the identifiers back.

The simplest observable example is the code.
`x = 2`

With no additional blank lines above it.

**Comment by vincentraymond-ua** [comment]
This is related to how we are using the line length sums when calculating an identifier on line 0.

There are two changes needed to fix this issue:

1. Initialize the line length sums List with 0 in index 0. 
```Python
self.line_length_sums = [0] + list(itertools.accumulate(self.line_lengths))
```

2. Update the logic for calculating the start_index.
```Python
start_index = self.line_length_sums[start_line] + start_column
```

**Comment by myedibleenso** [comment]
Needs test + PR
