### ISSUE TITLE
[code2FN] Label Generation in Gromet

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#752]
In order to support GOTO generation in Gromet, we need to add support for Label Generation in CAST, Annotated CAST, and Gromet.

```[tasklist]
### Tasks
- [x] CAST Generation (Vincent)
- [x] Annotated CAST Support
- [x] Gromet Generation
- [x] Unit Test
```

**Comment by titomeister** [comment]
Update Jan 19:
We've introduced the `Label` and `Goto` CAST nodes into the pipeline.
Also introduced the appropriate `Label` and `Goto` Annotated CAST elements in the pipeline. 
Current status is working on generating GroMEt FN for basic `Label` and `Goto`.

**Comment by titomeister** [comment]
Updated the issue to better reflect the development process.
