### ISSUE TITLE
[CISM] Generate full cism_v3 Gromet

### ISSUE THREAD

**Issue by vincentraymond-ua** [ml4ai/skema#766]
We need to generate a full Gromet FN for CISM (minus a few exceptional files).

Additionally, we want to generate some statistics based off the generated data:

- How many FNs
- How many files
- How many total lines

[cism_v3.zip](https://drive.google.com/file/d/18xeZLHPwHxV3esXIwH3kr28xD5me6ENw/view?usp=drive_link)

**Comment by myedibleenso** [comment]
@vincentraymond-ua , can you please resolve this with a PR link?

**Comment by vincentraymond-ua** [comment]
Resolved with #780
