### ISSUE TITLE
[M12] ISA support for model sustainment use cases

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#788]
[4.7] Extension of ISA to support model sustainment use cases through the TA4 interface.

```[tasklist]
### Tasks
```

**Comment by ualiangzhang** [comment]
Temporarily close this issue. If needed, we can reopen it.

- Added the use cases and evaluation [here](https://drive.google.com/drive/folders/16WfF09cfM7kCojMYPQvec2AlYUJSQwG3).
- Added the ISA documentation [here](https://docs.google.com/document/d/1rhBSkZLtBmPvaXjsNN1iMG8CED8F63kmmvX83YlKl_w/edit?usp=sharing).
- Added the notebook for ISA demos [here](https://github.com/ml4ai/ASKEM-TA1-DockerVM/blob/main/end-to-end-rest/notebooks/isa.ipynb).
